# .github/workflows/main.yml
name: Generate Contribution SVG

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # --- THIS IS THE FIX ---
    # Give the default GITHUB_TOKEN write permission to commit and push the changes
    permissions:
      contents: write
    # -----------------------

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Generate SVG
        run: node scripts/generate-eye.js
        env:
          GITTOKEN: ${{ secrets.GITTOKEN }}

      - name: Commit and Push SVG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Bot: Update contribution SVG'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          file_pattern: 'dist/eye.svg'
          repository: .
          branch: main
          push_options: '--force'