# This workflow is CORRECT for pushing to a separate 'output' branch
name: Generate The Eye Awakens SVG

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run script to generate SVG
        # This script must save the file inside a 'dist' folder
        # e.g., fs.writeFileSync('dist/eye.svg', svg);
        run: node scripts/generate-eye.js
        env:
          GITTOKEN: ${{ secrets.GITTOKEN }}

      - name: Commit and push the generated SVG
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # This tells the action to push to the 'output' branch
          target_branch: output
          # This tells the action to look for files inside the 'dist' folder
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}